ffosh:ffosh.cpp prompt.cpp parse.cpp parse_normal.cpp parse_set.cpp changedir.cpp expand.cpp expand_string.cpp execute.cpp redirect.cpp
	g++ -o ffosh -g -ggdb3 -Werror -Wall -pedantic -std=gnu++11 ffosh.cpp  prompt.cpp parse.cpp parse_normal.cpp parse_set.cpp changedir.cpp expand.cpp expand_string.cpp execute.cpp redirect.cpp
